### ISSUE TITLE
halting for errors vs `if (err) self.emit('error', err)`

### ISSUE THREAD

**Issue by timoxley** [mikeal/sequest#25]
Currently sequest doesn't seem to halt for errors, e.g.

```js
  this.connection.sftp(function (err, sftp) {
    if (err) self.emit('error', err) // no return
    var stream = sftp.createWriteStream(self.path, self.opts)
```

this leads to occasional `TypeError: Cannot read property 'createWriteStream' of undefined` errors due to missing `sftp`.

@mikeal do you recall what the reasoning was here?

**Comment by jcrugzz** [comment]
@timoxley seems like a bug to me.

**Comment by mikeal** [comment]
I don't recall, but I do remember that at some point I had to move to a newer version of the `ssh2` modules and many of these APIs changed during that transition. Perhaps this code never got migrated.
